x = input('Escreva algo para indertificar suas propriedades :')
print('O tipo primitivo desse valor e :',type(x))
print('So tem espacos?', x.isspace())
print('E um numero?', x.isnumeric())
print('E alfabetico?', x.isalpha())
print('E alfanumerico', x.isalnum())
print('Esta em minusculo?', x.islower())
print('Esta em maisculo?', x.isupper())
print('Esta capitalizada?', x.istitle())