numero = input('Digete um numero de 0 a 9999: ')
numero.split()
print('Unidade:{}'.format(numero[3]))
print('Dezena:{}'.format(numero[2]))
print('Centena:{}'.format(numero[1]))
print('Milhar:{}'.format(numero[0]))